# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty

# Setup
title:            Pierre Renault
tagline:          'Paysagiste concepteur'
description:      'Paysagiste concepteur'
url:              https://pierrenault.github.io/
baseurl:          https://pierrenault.github.io/

author:
  name:           'Pierre Renault'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:           pierrenault
  repo:           https://github.com/pierrenault/pierrenault.github.io.git          
