# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty

# Setup
title:            Pierre Renault - IngÃ©nieur paysagiste
tagline:          ''
description:      ''
url:              http://pierrenault.github.io/
baseurl:          http://pierrenault.github.io/

author:
  name:           'Pierre Renault'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           
